---
settings:
  name: BlueXP tiering
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: BlueXP 계층화 문서
    url: "/index.html"
  - title: 릴리스 정보
    url: "/whats-new.html"
  - title: 시작하십시오
    entries:
    - title: BlueXP 계층화에 대해 알아보십시오
      url: "/concept-cloud-tiering.html"
    - title: 사내 데이터를 클라우드로 계층화합니다
      entries:
      - title: Amazon S3에 계층화
        url: "/task-tiering-onprem-aws.html"
      - title: Azure Blob 저장소에 계층화
        url: "/task-tiering-onprem-azure.html"
      - title: Google Cloud Storage로 계층화합니다
        url: "/task-tiering-onprem-gcp.html"
      - title: StorageGRID로 계층화
        url: "/task-tiering-onprem-storagegrid.html"
      - title: S3 오브젝트 스토리지로 계층화합니다
        url: "/task-tiering-onprem-s3-compat.html"
    - title: 라이센스를 설정합니다
      url: "/task-licensing-cloud-tiering.html"
    - title: FAQ 를 참조하십시오
      url: "/faq-cloud-tiering.html"
  - title: BlueXP 계층화를 사용합니다
    entries:
    - title: 데이터 계층화 관리
      url: "/task-managing-tiering.html"
    - title: 오브젝트 스토리지 관리
      url: "/task-managing-object-storage.html"
    - title: 클라우드 성능 테스트
      url: "/task-tiering-test.html"
    - title: 모든 클러스터의 계층화 개요 보기
      url: "/task-tiering-onprem-overview.html"
  - title: 참조하십시오
    entries:
    - title: 지원되는 Amazon S3 스토리지 클래스 및 지역
      url: "/reference-aws-support.html"
    - title: 지원되는 Azure 액세스 계층 및 지역
      url: "/reference-azure-support.html"
    - title: 지원되는 Google Cloud 스토리지 클래스 및 지역
      url: "/reference-google-support.html"
  - title: 지식 및 지원
    entries:
    - title: 지원을 위해 등록하십시오
      url: "/task-support-registration.html"
    - title: 도움을 받으십시오
      url: "/task-get-help.html"
  - title: 법적 고지
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: BlueXP 계층화에 대해 알아보십시오
      url: concept-cloud-tiering.html
    - title: 새로운 기능
      url: whats-new.html
    - title: 라이센스를 설정합니다
      url: task-licensing-cloud-tiering.html
  - title: 사내 ONTAP 데이터를 클라우드에 계층화
    links:
    - title: Amazon S3에 계층화
      url: task-tiering-onprem-aws.html
    - title: Azure Blob에 계층화
      url: task-tiering-onprem-azure.html
    - title: Google Cloud로 계층화합니다
      url: task-tiering-onprem-gcp.html
    - title: StorageGRID로 계층화
      url: task-tiering-onprem-storagegrid.html
    - title: 일반 S3로 계층화
      url: task-tiering-onprem-s3-compat.html
  - title: 계층화 설정을 관리합니다
    links:
    - title: 볼륨의 계층화 정책을 변경합니다
      url: task-managing-tiering.html#changing-a-volumes-tiering-policy
    - title: 클러스터의 계층화 정보를 검토합니다
      url: task-managing-tiering.html#reviewing-tiering-info-for-a-cluster
    - title: 추가 볼륨의 데이터를 계층화합니다
      url: task-managing-tiering.html#tiering-data-from-additional-volumes
    - title: 클라우드에서 성능 계층으로 데이터 이동
      url: task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier
    - title: 애그리게이트에서 계층화 설정을 관리합니다
      url: task-managing-tiering.html#managing-tiering-settings-on-aggregates
  - title: 오브젝트 스토리지 관리
    links:
    - title: 클러스터에 대한 새 오브젝트 저장소를 추가합니다
      url: task-managing-object-storage.html#adding-a-new-object-store
    - title: 미러링을 위해 두 번째 오브젝트 저장소를 Aggregate에 추가합니다
      url: task-managing-object-storage.html#attaching-a-second-object-store-to-an-aggregate-for-mirroring
    - title: 운영 객체 저장소와 미러 객체 저장소를 바꿉니다
      url: task-managing-object-storage.html#swapping-the-primary-and-mirror-object-store
    - title: 미러 오브젝트 저장소를 제거합니다
      url: task-managing-object-storage.html#removing-a-mirror-object-store-from-an-aggregate
  - title: 블로그 커뮤니티
    links:
    - title: NetApp 커뮤니티
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: BlueXP 계층화 블로그 를 참조하십시오
      url: https://bluexp.netapp.com/blog/topic/cloud-tiering
    - title: 클라우드 웨비나
      url: https://bluexp.netapp.com/events
  - title: 기타 리소스
    links:
    - title: BlueXP 활용 사례
      url: https://bluexp.netapp.com/cloud-tiering
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: 모든 BlueXP 설명서
